apiVersion: apps/v1
kind: Deployment
metadata:
  name: harveymudd-demo
  namespace: demo
  labels:
    app: harveymudd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harveymudd
  template:
    metadata:
      labels:
        app: harveymudd
    spec:
      containers:
      - name: harveymudd
        image: us.gcr.io/marketforces-corp/harveymudd-demo:IMAGE_TAG
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: harveymudd
  namespace: demo
spec:
  selector:
    app: harveymudd
  ports:
    - protocol: TCP
      port: 80
