---
#resource_types:
  #- name: kubernetes
    #type: docker-image
    #source:
      #repository: zlabjp/kubernetes-resource
      #tag: "1.15"

resources:
  - name: harveymudd
    type: git
    icon: github-circle
    check_every: 3m
    source:
      uri: "https://github.com/loansnap/harveymudd.git"
      branch: "master"

jobs:
  - name: test
    plan:
    - get: harveymudd
      trigger: true
      version: every
    - task: some-task
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: node:10-alpine
        run:
          path: sh
          args:
          - -c
          - |
            cd harveymudd
            ls -l
            echo "MATT"
